services:
  # MongoDB database service.
  mongodb:
    container_name: appgrupal_mongodb
    image: mongo:8.2
    volumes:
      - ./mongodb_data:/data/db
      - ./mongodb_config:/data/configdb
    env_file:
      - ./docker-compose.env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - appgrupal_net

  # Backend API service.
  backend:
    container_name: appgrupal_backend
    build:
      context: ./backend
      dockerfile: docker/dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./docker-compose.env
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - appgrupal_net

  # Frontend Angular service (development server).
  frontend:
    container_name: appgrupal_frontend
    build:
      context: ./frontend/client
      dockerfile: docker/dockerfile
    ports:
      - "4000:4200"
    depends_on:
      - backend
    env_file:
      - ./docker-compose.env
    restart: unless-stopped
    networks:
      - appgrupal_net

networks:
  appgrupal_net:
