# Use an official Node.js runtime as the base image.
FROM node:24

# Attach image metadata for traceability and maintenance.
LABEL version="1.0.0"
LABEL maintainer="opendicom <opendicom@gmail.com>"
LABEL author="Mia <mimiscele11@gmail.com>"
LABEL description="app grupal"


ENV NODE_ENV=production


EXPOSE 3000

# Set the working directory inside the container.
WORKDIR /app

# Copy dependency manifests first to leverage Docker build cache.
COPY backend/package*.json ./

# Install only production dependencies.
RUN npm install --omit=dev


# Copy the backend source code into the image.
COPY backend/. .

# Copy the database folder to the image (needed for entrypoint.sh)
COPY database ./database

# Copy container startup script and place it at the app root.
COPY backend/docker/entrypoint.sh ./entrypoint.sh


RUN chmod 755 ./entrypoint.sh

# Start the container through the entrypoint script.
ENTRYPOINT ["./entrypoint.sh"]